shoujin: 8023
password: '{cipher}AQA8LnBrMl6tVkqyTEnLA2qsWe4lVoFINZdqpkuD1JD5Y7bCAWML6rhIMiQPga41gAWS5ju0nFrzLIwXts2aZFFA6icuYLoUrfoquVdY8cGPO+dn9Vxlv67/yCGkahb80/Dx1cg8INcRleuKLqehHeTYKB3mn9wsDli96Tq9Tt9Na6eyS0kmfKQB0H8pp7uVIC5eOxEmsj8dyFG8SDtFcCevgONcImvXXjWH8Ck3p35quzrmlOKIXBRoEjd6K25+BYwCUJB2K1Nf3j2HxzMEdF3plsPfEMKKfciD1ywMXqq4PQskem0M0tV8XPFDfcCBIjWsI91aDl8cp22eg1+xnoNIieyqP0XP3VVTEm5t79SEdLZsu5Ew5A6b9e1iGIjU+O8='
user:
    userName: dev/xjch
    sex: ç”·
    age: 18